<a href="https://colab.research.google.com/github/NisargKadam/AIFabricUiPath/blob/main/NumPy_Nisarg_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning NumPy from scratch

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])                 # 1D array
print(a)

[1 2 3]


In [ ]:
b = np.array([[1, 2], [3, 4]])          # 2D array
print(b)

[[1 2]
 [3 4]]


In [ ]:
c = np.zeros((2, 3))                    # 2x3 array of zeros
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
d = np.ones((3, 3))                     # 3x3 array of ones
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
e = np.eye(4)                           # 4x4 identity matrix
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
f = np.arange(0, 10, 2)                 # [0, 2, 4, 6, 8]
print(f)

[0 2 4 6 8]


In [ ]:
g = np.linspace(0, 1, 5)                # 5 points between 0 and 1
print(g)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
h = np.random.rand(2, 3)                # 2x3 array of random floats (0-1)
print(h)

[[0.61276607 0.24105701 0.32006329]
 [0.42149602 0.36106715 0.8427343 ]]


In [ ]:
i = np.full((2,2), 7)                   # 2x2 array of 7s
print(i)

[[7 7]
 [7 7]]


Array Attributes

In [ ]:
a.shape         # returns (n,) tuple: dimensions

(3,)

In [ ]:
a.size          # total number of elements

3

In [ ]:
a.dtype         # data type (e.g., int64, float32)

dtype('int64')

In [ ]:
a.ndim          # number of dimensions (axes)

1

In [ ]:
a.itemsize      # size in bytes of one element

8

Indexing and Slicing

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [ ]:
arr[0, 1]                # 20 (row 0, col 1)

np.int64(20)

In [ ]:
arr[:, 1]                # [20, 50] (all rows, col 1)

array([20, 50])

In [ ]:
arr[1, :]                # [40, 50, 60] (row 1, all cols)

array([40, 50, 60])

In [ ]:
arr[0:2, 1:3]            # [[20, 30], [50, 60]]

array([[20, 30],
       [50, 60]])

In [ ]:
arr[-1]                  # last row

array([40, 50, 60])

In [ ]:
arr[::2]                 # every 2nd row

array([[10, 20, 30]])

In [ ]:
arr[::-1]

array([[40, 50, 60],
       [10, 20, 30]])

Array Maths Operations

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

In [ ]:
x + y         # [11, 22, 33]

array([11, 22, 33])

In [ ]:
x * y         # [10, 40, 90]

array([10, 40, 90])

In [ ]:
x / 2         # [0.5, 1.0, 1.5]

array([0.5, 1. , 1.5])

In [ ]:
x ** 2        # [1, 4, 9]

array([1, 4, 9])

In [ ]:
np.sqrt(x)    # [1., 1.414, 1.732]

array([1.        , 1.41421356, 1.73205081])

In [ ]:
x > 1

array([False,  True,  True])

In [ ]:
np.any(x>1)

np.True_

In [ ]:
np.all(x>0)

np.True_

Agrregate Functions

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [ ]:
arr.sum()

np.int64(210)

In [ ]:
arr.mean()

np.float64(35.0)

In [ ]:
arr.min()

np.int64(10)

In [ ]:
arr.max()

np.int64(60)

In [ ]:
arr.std()

np.float64(17.07825127659933)

In [ ]:
arr.var()

np.float64(291.6666666666667)

In [ ]:
arr.sum(axis=0)   # sum down columns

array([50, 70, 90])

In [ ]:
arr.sum(axis=1)   # sum across rows

array([ 60, 150])

Reshaping

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
a.reshape(2,3) #reshape(Number of rows, number of columns)

array([[0, 1, 2],
       [3, 4, 5]])

Stacking

In [ ]:
np.vstack([a,a]) #vertically stack array a

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [ ]:
np.hstack([a,a]) #horizontally stack array a

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [ ]:
np.concatenate([a,a], axis=0)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

Splitting

In [ ]:
np.split(arr, 2, axis=0)

[array([[10, 20, 30]]), array([[40, 50, 60]])]

In [ ]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.vsplit(arr, 2)

[array([[10, 20, 30]]), array([[40, 50, 60]])]

Boolean Indexing

In [ ]:
arr = np.array([1,2,3,4,5])
mask = arr>3
arr[mask]

array([4, 5])

In [ ]:
arr[arr%2 == 0]

array([2, 4])

In [ ]:
arr % 2 == 0

array([False,  True, False,  True, False])

Useful array methods

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr.T

array([1, 2, 3, 4, 5])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr1.T # transpose the array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
arr1.flatten() #convert entire array to 1D array

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1.ravel() #flattens and returns view

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1.copy()

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.clip(0,4)

array([[1, 2, 3],
       [4, 4, 4]])

In [ ]:
arr1.argsort()

array([[0, 1, 2],
       [0, 1, 2]])

In [ ]:
arr1.sort(axis=0) #in place sort
print(arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2 = np.array([1,2,3,4,4,4,4,4,5,5])
np.unique(arr2)

array([1, 2, 3, 4, 5])

In [ ]:
np.where(arr1 > 3, 1, -1)

array([[-1, -1, -1],
       [ 1,  1,  1]])

random function

In [ ]:
np.random.seed(1)

In [ ]:
np.random.rand(2,3)  # 2x3 array of floats [0,1)

array([[0.24621107, 0.86002795, 0.53883106],
       [0.55282198, 0.84203089, 0.12417332]])

In [ ]:
np.random.randint(0,10,(2,4))

array([[3, 4, 2, 0],
       [3, 5, 1, 2]])